1erParcialPracticoWeb3/AreasDeFiguras.Web3/AreasDeFiguras.Web3/Models/ErrorViewModel.cs
namespace AreasDeFiguras.Web3.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

1erParcialPracticoWeb3/AreasDeFiguras.Web3/AreasDeFiguras.Web3/Models/FiguraModel.cs
namespace AreasDeFiguras.Web3.Models
{
    public class FiguraModel
    {
        public int Id { get; set; }
        public int baseFigura { get; set; }
        public int alturaFigura { get; set; }
        public int areaFigura { get; set; }
    }
}

1erParcialPracticoWeb3/AreasDeFiguras.Web3/AreasDeFiguras.Web3/Models/RectanguloModel.cs
using AreasDeFiguras.Entidades;

namespace AreasDeFiguras.Web3.Models
{
    public class RectanguloModel : FiguraModel
    {
        public RectanguloModel() { }

        public RectanguloModel(RectanguloFigura rectangulo) {
            Id = rectangulo.Id;
            baseFigura = rectangulo.baseFigura;
            alturaFigura = rectangulo.alturaFigura;
            areaFigura = rectangulo.areaFigura;
        }


        internal static object MapearAListaModel(List<RectanguloFigura> rectangulos)
        {
            return rectangulos.Select(r => new RectanguloModel(r)).ToList();
        }

        internal RectanguloFigura MapToEntity()
        {
            return new RectanguloFigura
            {
                Id = Id,
                baseFigura = baseFigura,
                alturaFigura = alturaFigura,
                areaFigura = areaFigura
            };
        }
    }
}

1erParcialPracticoWeb3/AreasDeFiguras.Web3/AreasDeFiguras.Web3/Controllers/HomeController.cs
using AreasDeFiguras.Web3.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AreasDeFiguras.Web3.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

1erParcialPracticoWeb3/AreasDeFiguras.Web3/AreasDeFiguras.Web3/Controllers/PrincipalController.cs
using AreasDeFiguras.Entidades;
using AreasDeFiguras.Servicios;
using AreasDeFiguras.Web3.Models;
using Microsoft.AspNetCore.Mvc;

namespace AreasDeFiguras.Web3.Controllers
{
    public class PrincipalController : Controller
    {
        public readonly IFigurasService _figuraService;

        public PrincipalController(IFigurasService figuraService)
        {
            _figuraService = figuraService;
        }
        public IActionResult Bienvenido()
        {
            return View();
        }

        public IActionResult Resultados()
        {
            var rectangulos = _figuraService.ObtenerRectangulos();
            var rectangulosListaModel = RectanguloModel.MapearAListaModel(rectangulos);
            return View(rectangulosListaModel);
        }

        public IActionResult CalcularAreaDeFiguras()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CalcularAreaDeFiguras(RectanguloModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            _figuraService.CalcularArea(model.MapToEntity());
            return RedirectToAction("Resultados");
        }
    }
}

1erParcialPracticoWeb3/AreasDeFiguras.Web3/AreasDeFiguras.Web3/Views/Principal/Bienvenido.cshtml
<h1>Bienvenido al sitio de evaluación</h1>

1erParcialPracticoWeb3/AreasDeFiguras.Web3/AreasDeFiguras.Web3/Views/Principal/CalcularAreaDeFiguras.cshtml
@model RectanguloModel
<h3>Calculador de Áreas de Figuras Rectángulos en metros</h3>
<form action="/Principal/CalcularAreaDeFiguras" method="post">
    @Html.AntiForgeryToken()
    <div class="form-group">
        @Html.LabelFor(model => model.baseFigura)
        @Html.TextBoxFor(model => model.baseFigura, new { @class = "form-control", type = "number" })
        @Html.ValidationMessageFor(model => model.baseFigura, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.alturaFigura)
        @Html.TextBoxFor(model => model.alturaFigura, new { @class = "form-control", type = "number" })
        @Html.ValidationMessageFor(model => model.alturaFigura, "", new { @class = "text-danger" })
    </div>
    <button type="submit" class="btn btn-primary">Calcular</button>
</form>
@section Scripts {
    <partial name="_ValidationScriptsPartial"/>
}

1erParcialPracticoWeb3/AreasDeFiguras.Web3/AreasDeFiguras.Web3/Views/Principal/Resultados.cshtml
@model List<RectanguloModel>

<h1>Resultados</h1>
<div>
    <a href="/Principal/Bienvenido">Pagina Principal</a>
</div>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Calculo</th>
            <th>Base</th>
            <th>Altura</th>
            <th>=</th>
            <th>Resultado</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var rectangulo in Model)
        {
            <tr>
                <td>Calculo @rectangulo.Id</td>
                <td>@rectangulo.baseFigura</td>
                <td>@rectangulo.alturaFigura</td>
                <td>=</td>
                <td>@rectangulo.areaFigura</td>
            </tr>
        }
    </tbody>
</table>

1erParcialPracticoWeb3/AreasDeFiguras.Web3/AreasDeFiguras.Web3/Views/Shared/_FigurasLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AreasDeFiguras.Web3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AreasDeFiguras.Web3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AreasDeFiguras.Web3</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Principal" asp-action="Resultados">Resultados</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Principal" asp-action="CalcularAreaDeFiguras">Hacer Calculo</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AreasDeFiguras.Web3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

1erParcialPracticoWeb3/AreasDeFiguras.Web3/AreasDeFiguras.Web3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AreasDeFiguras.Web3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AreasDeFiguras.Web3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AreasDeFiguras.Web3</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AreasDeFiguras.Web3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>